// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SahinBankApp.Data.Concrete.EFCore;

#nullable disable

namespace SahinBankApp.Data.Migrations
{
    [DbContext(typeof(SahinBankAppDbContext))]
    partial class SahinBankAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("SahinBankApp.Entity.ActionMove", b =>
                {
                    b.Property<int>("ActionMoveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ActionAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ActionDeduction")
                        .HasColumnType("TEXT");

                    b.Property<int>("ActionTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("ActionMoveId");

                    b.HasIndex("ActionTypeId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("SahinBankApp.Entity.ActionType", b =>
                {
                    b.Property<int>("ActionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionTypeDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionTypeName")
                        .HasColumnType("TEXT");

                    b.HasKey("ActionTypeId");

                    b.ToTable("ActionTypes");
                });

            modelBuilder.Entity("SahinBankApp.Entity.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InvoiceDueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceOwner")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("InvoiceId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("SahinBankApp.Entity.ActionMove", b =>
                {
                    b.HasOne("SahinBankApp.Entity.ActionType", "ActionType")
                        .WithMany()
                        .HasForeignKey("ActionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SahinBankApp.Entity.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId");

                    b.Navigation("ActionType");

                    b.Navigation("Invoice");
                });
#pragma warning restore 612, 618
        }
    }
}
